<?php
/*
 * This file is part of Aplus Framework MVC Library.
 *
 * (c) Natan Felles <natanfelles@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Tests\MVC;

use Framework\Config\Config;
use Framework\Language\Language;
use Framework\MVC\Debug\AppCollector;

class AppMock extends \Framework\MVC\App
{
    public function loadConfigs(string $name) : array | null
    {
        return parent::loadConfigs($name);
    }

    public static function setDebugCollector(AppCollector $debugCollector) : void
    {
        static::$debugCollector = $debugCollector;
    }

    public static function setServerVars(array $vars = []) : void
    {
        parent::setServerVars($vars); // TODO: Change the autogenerated stub
    }

    public static function setConfigProperty(?Config $config) : void
    {
        static::$config = $config;
    }

    public static function negotiateLanguage(Language $language, string $requestInstance = 'default') : string
    {
        return parent::negotiateLanguage($language, $requestInstance);
    }

    public static function notService(mixed $instance = 'default') : void
    {
    }
}
