name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept Pull Requests on GitHub! Please, open a PR in [GitLab](https://gitlab.com/aplus-framework/libraries/mvc)."
